### ISSUE TITLE
ERR Deadline exceeded while waiting for data from the queue!

### ISSUE THREAD

**Issue by ssdutHB** [brownvc/ganimorph#5]
I rename my dataset folder as trainA, trainB, testA and TestB. Then I install the tensorpack with the required version. However, the training process is stopped by "ERR Deadline exceeded while waiting for data from the queue!".
Here is the traceback:

  0%|          |0/1000[00:00<?,?it/s] Start Epoch 1 ...
2018-08-24 14:30:39.133698: W tensorflow/core/kernels/queue_base.cc:295] _0_input_queue: Skipping cancelled enqueue attempt with queue not closed
[0824 14:30:39 @input_source.py:204] ERR Deadline exceeded while waiting for data from the queue!
Traceback (most recent call last):
  File "/media/he/80FE99D1FE99BFB8/ganimorph/ganimorph/tensorpack/train/input_source.py", line 200, in run
    sess.run(self.op, feed_dict=feed, options=opt)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
DeadlineExceededError: Timed out waiting for notification
[0824 14:30:39 @input_source.py:212] EnqueueThread Exited.
[0824 14:30:50 @base.py:200] Training was stopped.
2018-08-24 14:30:50.966173: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: FIFOQueue '_0_input_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: input_deque = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_queue)]]
2018-08-24 14:30:50.966501: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: FIFOQueue '_0_input_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: input_deque = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_queue)]]
  4%|3         |35/1000[00:36<16:52, 0.95it/s]
Prefetch process exited.
Prefetch process exited.
Prefetch process exited.
Prefetch process exited.

Process finished with exit code 0

Could you please tell me how I can fix it?

**Comment by ssdutHB** [comment]
It seems that I have modified something unexpectedly. After I clone the project once again, it works.

**Comment by lzhbrian** [comment]
Hi @ssdutHB , I am experiencing the same issue, could you please share your solution? What have you modified?
Thanks
